// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.28.3
// source: admin_management.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_EntityType_User    EntityType = 0
	EntityType_EntityType_Company EntityType = 1
	EntityType_EntityType_Hotel   EntityType = 2
	EntityType_EntityType_Agency  EntityType = 3
	EntityType_EntityType_Vehicle EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "EntityType_User",
		1: "EntityType_Company",
		2: "EntityType_Hotel",
		3: "EntityType_Agency",
		4: "EntityType_Vehicle",
	}
	EntityType_value = map[string]int32{
		"EntityType_User":    0,
		"EntityType_Company": 1,
		"EntityType_Hotel":   2,
		"EntityType_Agency":  3,
		"EntityType_Vehicle": 4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_management_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_admin_management_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{0}
}

type BannedEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BanId      string                 `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
	EntityType EntityType             `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=EntityType" json:"entity_type,omitempty"`
	EntityId   string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason     string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	StartAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *BannedEntity) Reset() {
	*x = BannedEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannedEntity) ProtoMessage() {}

func (x *BannedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannedEntity.ProtoReflect.Descriptor instead.
func (*BannedEntity) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{0}
}

func (x *BannedEntity) GetBanId() string {
	if x != nil {
		return x.BanId
	}
	return ""
}

func (x *BannedEntity) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_EntityType_User
}

func (x *BannedEntity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *BannedEntity) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BannedEntity) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *BannedEntity) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type BanEntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType string `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId   string `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason     string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BanEntityRequest) Reset() {
	*x = BanEntityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanEntityRequest) ProtoMessage() {}

func (x *BanEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanEntityRequest.ProtoReflect.Descriptor instead.
func (*BanEntityRequest) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{1}
}

func (x *BanEntityRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *BanEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *BanEntityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanEntityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BanEntityResponse) Reset() {
	*x = BanEntityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanEntityResponse) ProtoMessage() {}

func (x *BanEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanEntityResponse.ProtoReflect.Descriptor instead.
func (*BanEntityResponse) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{2}
}

func (x *BanEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnbanEntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BanId string `protobuf:"bytes,1,opt,name=ban_id,json=banId,proto3" json:"ban_id,omitempty"`
}

func (x *UnbanEntityRequest) Reset() {
	*x = UnbanEntityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanEntityRequest) ProtoMessage() {}

func (x *UnbanEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanEntityRequest.ProtoReflect.Descriptor instead.
func (*UnbanEntityRequest) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{3}
}

func (x *UnbanEntityRequest) GetBanId() string {
	if x != nil {
		return x.BanId
	}
	return ""
}

type UnbanEntityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UnbanEntityResponse) Reset() {
	*x = UnbanEntityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanEntityResponse) ProtoMessage() {}

func (x *UnbanEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanEntityResponse.ProtoReflect.Descriptor instead.
func (*UnbanEntityResponse) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{4}
}

func (x *UnbanEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // TODO: please add more filters
}

func (x *CheckHistoryRequest) Reset() {
	*x = CheckHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHistoryRequest) ProtoMessage() {}

func (x *CheckHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHistoryRequest.ProtoReflect.Descriptor instead.
func (*CheckHistoryRequest) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{5}
}

func (x *CheckHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report string `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *CheckHistoryResponse) Reset() {
	*x = CheckHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHistoryResponse) ProtoMessage() {}

func (x *CheckHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHistoryResponse.ProtoReflect.Descriptor instead.
func (*CheckHistoryResponse) Descriptor() ([]byte, []int) {
	return file_admin_management_proto_rawDescGZIP(), []int{6}
}

func (x *CheckHistoryResponse) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

var File_admin_management_proto protoreflect.FileDescriptor

var file_admin_management_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x01, 0x0a, 0x0c, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x61,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x61, 0x6e, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x65,
	0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x68,
	0x0a, 0x10, 0x42, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x11, 0x42, 0x61, 0x6e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2b, 0x0a, 0x12, 0x55, 0x6e, 0x62, 0x61, 0x6e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x62, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x61, 0x6e, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x2a, 0x7e, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x10, 0x01,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x10, 0x03, 0x12, 0x16, 0x0a,
	0x12, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x10, 0x04, 0x32, 0xc3, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x32, 0x0a, 0x09, 0x42, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x11, 0x2e,
	0x42, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x42, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x13, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x51, 0x42, 0x43, 0x38, 0x2d, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x35, 0x2f, 0x67, 0x68, 0x6f, 0x6c, 0x69, 0x62, 0x61, 0x62, 0x61, 0x5f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_management_proto_rawDescOnce sync.Once
	file_admin_management_proto_rawDescData = file_admin_management_proto_rawDesc
)

func file_admin_management_proto_rawDescGZIP() []byte {
	file_admin_management_proto_rawDescOnce.Do(func() {
		file_admin_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_management_proto_rawDescData)
	})
	return file_admin_management_proto_rawDescData
}

var file_admin_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_management_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_management_proto_goTypes = []interface{}{
	(EntityType)(0),               // 0: EntityType
	(*BannedEntity)(nil),          // 1: BannedEntity
	(*BanEntityRequest)(nil),      // 2: BanEntityRequest
	(*BanEntityResponse)(nil),     // 3: BanEntityResponse
	(*UnbanEntityRequest)(nil),    // 4: UnbanEntityRequest
	(*UnbanEntityResponse)(nil),   // 5: UnbanEntityResponse
	(*CheckHistoryRequest)(nil),   // 6: CheckHistoryRequest
	(*CheckHistoryResponse)(nil),  // 7: CheckHistoryResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_admin_management_proto_depIdxs = []int32{
	0, // 0: BannedEntity.entity_type:type_name -> EntityType
	8, // 1: BannedEntity.start_at:type_name -> google.protobuf.Timestamp
	8, // 2: BannedEntity.end_at:type_name -> google.protobuf.Timestamp
	2, // 3: AdminManagementService.BanEntity:input_type -> BanEntityRequest
	4, // 4: AdminManagementService.UnbanEntity:input_type -> UnbanEntityRequest
	6, // 5: AdminManagementService.CheckHistory:input_type -> CheckHistoryRequest
	3, // 6: AdminManagementService.BanEntity:output_type -> BanEntityResponse
	5, // 7: AdminManagementService.UnbanEntity:output_type -> UnbanEntityResponse
	7, // 8: AdminManagementService.CheckHistory:output_type -> CheckHistoryResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_management_proto_init() }
func file_admin_management_proto_init() {
	if File_admin_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannedEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanEntityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanEntityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanEntityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanEntityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_management_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_management_proto_goTypes,
		DependencyIndexes: file_admin_management_proto_depIdxs,
		EnumInfos:         file_admin_management_proto_enumTypes,
		MessageInfos:      file_admin_management_proto_msgTypes,
	}.Build()
	File_admin_management_proto = out.File
	file_admin_management_proto_rawDesc = nil
	file_admin_management_proto_goTypes = nil
	file_admin_management_proto_depIdxs = nil
}
