// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: transportation_company.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransportationCompanyService_CreateTrip_FullMethodName          = "/TransportationCompanyService/CreateTrip"
	TransportationCompanyService_UpdateTripStatus_FullMethodName    = "/TransportationCompanyService/UpdateTripStatus"
	TransportationCompanyService_AssignTechnicalTeam_FullMethodName = "/TransportationCompanyService/AssignTechnicalTeam"
	TransportationCompanyService_ListCompanyTrips_FullMethodName    = "/TransportationCompanyService/ListCompanyTrips"
)

// TransportationCompanyServiceClient is the client API for TransportationCompanyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransportationCompanyServiceClient interface {
	CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error)
	UpdateTripStatus(ctx context.Context, in *UpdateTripStatusRequest, opts ...grpc.CallOption) (*UpdateTripStatusResponse, error)
	AssignTechnicalTeam(ctx context.Context, in *AssignTechnicalTeamRequest, opts ...grpc.CallOption) (*AssignTechnicalTeamResponse, error)
	ListCompanyTrips(ctx context.Context, in *ListCompanyTripsRequest, opts ...grpc.CallOption) (*ListCompanyTripsResponse, error)
}

type transportationCompanyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransportationCompanyServiceClient(cc grpc.ClientConnInterface) TransportationCompanyServiceClient {
	return &transportationCompanyServiceClient{cc}
}

func (c *transportationCompanyServiceClient) CreateTrip(ctx context.Context, in *CreateTripRequest, opts ...grpc.CallOption) (*CreateTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTripResponse)
	err := c.cc.Invoke(ctx, TransportationCompanyService_CreateTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportationCompanyServiceClient) UpdateTripStatus(ctx context.Context, in *UpdateTripStatusRequest, opts ...grpc.CallOption) (*UpdateTripStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTripStatusResponse)
	err := c.cc.Invoke(ctx, TransportationCompanyService_UpdateTripStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportationCompanyServiceClient) AssignTechnicalTeam(ctx context.Context, in *AssignTechnicalTeamRequest, opts ...grpc.CallOption) (*AssignTechnicalTeamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignTechnicalTeamResponse)
	err := c.cc.Invoke(ctx, TransportationCompanyService_AssignTechnicalTeam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transportationCompanyServiceClient) ListCompanyTrips(ctx context.Context, in *ListCompanyTripsRequest, opts ...grpc.CallOption) (*ListCompanyTripsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCompanyTripsResponse)
	err := c.cc.Invoke(ctx, TransportationCompanyService_ListCompanyTrips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransportationCompanyServiceServer is the server API for TransportationCompanyService service.
// All implementations must embed UnimplementedTransportationCompanyServiceServer
// for forward compatibility.
type TransportationCompanyServiceServer interface {
	CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error)
	UpdateTripStatus(context.Context, *UpdateTripStatusRequest) (*UpdateTripStatusResponse, error)
	AssignTechnicalTeam(context.Context, *AssignTechnicalTeamRequest) (*AssignTechnicalTeamResponse, error)
	ListCompanyTrips(context.Context, *ListCompanyTripsRequest) (*ListCompanyTripsResponse, error)
	mustEmbedUnimplementedTransportationCompanyServiceServer()
}

// UnimplementedTransportationCompanyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransportationCompanyServiceServer struct{}

func (UnimplementedTransportationCompanyServiceServer) CreateTrip(context.Context, *CreateTripRequest) (*CreateTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrip not implemented")
}
func (UnimplementedTransportationCompanyServiceServer) UpdateTripStatus(context.Context, *UpdateTripStatusRequest) (*UpdateTripStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTripStatus not implemented")
}
func (UnimplementedTransportationCompanyServiceServer) AssignTechnicalTeam(context.Context, *AssignTechnicalTeamRequest) (*AssignTechnicalTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTechnicalTeam not implemented")
}
func (UnimplementedTransportationCompanyServiceServer) ListCompanyTrips(context.Context, *ListCompanyTripsRequest) (*ListCompanyTripsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCompanyTrips not implemented")
}
func (UnimplementedTransportationCompanyServiceServer) mustEmbedUnimplementedTransportationCompanyServiceServer() {
}
func (UnimplementedTransportationCompanyServiceServer) testEmbeddedByValue() {}

// UnsafeTransportationCompanyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransportationCompanyServiceServer will
// result in compilation errors.
type UnsafeTransportationCompanyServiceServer interface {
	mustEmbedUnimplementedTransportationCompanyServiceServer()
}

func RegisterTransportationCompanyServiceServer(s grpc.ServiceRegistrar, srv TransportationCompanyServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransportationCompanyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransportationCompanyService_ServiceDesc, srv)
}

func _TransportationCompanyService_CreateTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportationCompanyServiceServer).CreateTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransportationCompanyService_CreateTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportationCompanyServiceServer).CreateTrip(ctx, req.(*CreateTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportationCompanyService_UpdateTripStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTripStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportationCompanyServiceServer).UpdateTripStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransportationCompanyService_UpdateTripStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportationCompanyServiceServer).UpdateTripStatus(ctx, req.(*UpdateTripStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportationCompanyService_AssignTechnicalTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTechnicalTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportationCompanyServiceServer).AssignTechnicalTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransportationCompanyService_AssignTechnicalTeam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportationCompanyServiceServer).AssignTechnicalTeam(ctx, req.(*AssignTechnicalTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransportationCompanyService_ListCompanyTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompanyTripsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransportationCompanyServiceServer).ListCompanyTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransportationCompanyService_ListCompanyTrips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransportationCompanyServiceServer).ListCompanyTrips(ctx, req.(*ListCompanyTripsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransportationCompanyService_ServiceDesc is the grpc.ServiceDesc for TransportationCompanyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransportationCompanyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TransportationCompanyService",
	HandlerType: (*TransportationCompanyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrip",
			Handler:    _TransportationCompanyService_CreateTrip_Handler,
		},
		{
			MethodName: "UpdateTripStatus",
			Handler:    _TransportationCompanyService_UpdateTripStatus_Handler,
		},
		{
			MethodName: "AssignTechnicalTeam",
			Handler:    _TransportationCompanyService_AssignTechnicalTeam_Handler,
		},
		{
			MethodName: "ListCompanyTrips",
			Handler:    _TransportationCompanyService_ListCompanyTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transportation_company.proto",
}
